DROP TABLE IF EXISTS player_statistics CASCADE;
DROP TABLE IF EXISTS team_statistics CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS seasons CASCADE;
-- DROP TABLE IF EXISTS leagues CASCADE;
-- DROP TABLE IF EXISTS timezones CASCADE;
-- DROP TABLE IF EXISTS countries CASCADE;
