TRUNCATE TABLE player_statistics RESTART IDENTITY CASCADE;
TRUNCATE TABLE team_statistics RESTART IDENTITY CASCADE;
TRUNCATE TABLE players RESTART IDENTITY CASCADE;
TRUNCATE TABLE teams RESTART IDENTITY CASCADE;
TRUNCATE TABLE seasons RESTART IDENTITY CASCADE;
TRUNCATE TABLE leagues RESTART IDENTITY CASCADE;
TRUNCATE TABLE timezones RESTART IDENTITY CASCADE;
TRUNCATE TABLE countries RESTART IDENTITY CASCADE;